##Common config for all profiles
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.server.user.name}:${eureka.server.user.password}@localhost:8761/eureka/
    healthcheck:
      enabled: false
  server:
    user:
      name: username
      password: password